title: "Z-Blog"   # your title
author: "年轻人" # your name
description: "用于期待更好的想法！" # your description
avatar: /images/avatar.png # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 8
paginate_path: "/page:num/"
gems: [jekyll-paginate]

Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics
